import express from 'express';
import { singleUpload } from '../middleware/multer.js';
import isAuthenticated from '../middleware/isAuthentic.js';
import {login,logout,register,updateProfile} from "../controllers/user.controller.js";
const router =express.Router();
router.route("/register").post(singleUpload, register);
router.route("/login").post(login);
router.route("/logout").get(logout);
router.route("/profile/update").post(isAuthenticated,singleUpload,updateProfile);
export default router;